name: GitHub Actions Version Notification

# Controls when the action will run.
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run GitHub Actions Version Updater
        uses: RutujaK2211/Github-version-notify@main
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_SECRET }}
          ignore: 'RutujaK2211/Github-version-notify@main'
          release_types: "major"
